-- Active: 1651820926135@@127.0.0.1@3306@6289530166319
CREATE TABLE menu(
  id_menu INT AUTO_INCREMENT PRIMARY KEY,
  id_kategori INT,
  image VARCHAR(50),
  judul VARCHAR(100),
  deskripsi TEXT,
  harga INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DELIMITER / / 
CREATE TRIGGER before_update_menu BEFORE
UPDATE
  ON menu FOR EACH ROW BEGIN
SET
  NEW.updated_at = NOW();

END;

/ / DELIMITER;